#! /usr/bin/env ruby
require "pg"

# This is the execution class, we need some sort of 'run' method I think
class CLI
  def initialize
    @expenses = ExpenseData.new
  end

  def display_help
    puts <<~MSG
    Welcome to the CLI expense recording system.

    Commands:

    add AMOUNT MEMO [DATE] - record a new expense
    clear - delete all expenses
    list - list all expenses
    delete NUMBER - remove expense with id NUMBER
    search QUERY - list expenses with a matching memo field
    MSG
  end

  def execute
    # When writing a script, we can access the list of arguments passed into a command-line program with ARGV. 
    # ARGV will be an Array of arguments that have been passed to your command-line program.
    case ARGV.first
    when "list"
      @expenses.list_expense
    when "add"
      if ARGV.size == 3 
        @expenses.add_expense(ARGV[1], ARGV[2]) 
      else 
        puts "You must provide an amount and memo."
      end
    when "search"
      @expenses.search_expense(ARGV[1])
    when "delete"
      @expenses.delete_expense(ARGV[1])
    when "clear"
      @expenses.clear_expense
    else
      display_help
    end
  end
end

class ExpenseData
  def initialize
    @db = PG.connect(dbname:"expenses")
  end

  def add_expense(amount, memo)
    date = Date.today
    @db.exec_params("
      INSERT INTO expenses (amount, memo, created_on)
        VALUES ($1, $2, $3);", [amount, memo, date])
  end

  def list_expense
    results = @db.exec("SELECT * FROM expenses ORDER BY created_on ASC;")
    display_expenses(results)
  end

  def search_expense(term)
    filtered_results = @db.exec_params("SELECT * FROM expenses WHERE memo ILIKE $1", ["%#{term}%"])
    display_expenses(filtered_results)
  end

  def delete_expense(id)
    puts "There is no expense with the id '#{id}'." unless valid_expense?(id)

    if valid_expense?(id)
      deleted_row = @db.exec_params("SELECT * FROM expenses where id = $1", [id])
      @db.exec_params("DELETE FROM expenses WHERE id = $1", [id])
      puts "The following expense has been deleted:"
      display_expenses(deleted_row)
    end
  end

  def clear_expense
    # Update CLI class
    # Display warning message
      # User inputs y or n
        # Validate this y or n
      # If user says 'n', break out of a loop
      # If user says 'y', execute DELETE FROM expenses
        # Display a message
  end

  private

  def valid_expense?(id)
    @db.exec_params("SELECT * FROM expenses WHERE id = $1", [id]).ntuples == 1
  end

  def display_expenses(obj)
    obj.each do |tuple|
      row = [tuple["id"].rjust(3), tuple["created_on"].rjust(10), tuple["amount"].rjust(8), tuple["memo"]]
      puts row.join(" | ")
    end
  end
end

CLI.new.execute
